version: '3.2'
networks:
  private:
  public:
    external:
      name: traefik_webgateway
services:
  nginx:
    image: nginx:alpine
    command: ["nginx", "-g", "daemon off;"]
    labels:
      - traefik.backend=${COMPOSE_PROJECT_NAME}-nginx
      - traefik.docker.network=traefik_webgateway
      - traefik.frontend.rule=Host:${COMPOSE_PROJECT_NAME}.localhost
      - traefik.port=8080
    networks:
      - public
      - private
    volumes:
      - ${PWD}/testing/index.php:/var/www/index.php
      - ${PWD}/testing/vhost.conf:/etc/nginx/conf.d/default.conf
  php:
    image: jtreminio/php:7.2
    command: /usr/bin/php-fpm
    networks:
      - private
    volumes:
      - ${PWD}/testing/index.php:/var/www/index.php

  nginx-de:
    image: nginx:alpine
    command: ["nginx", "-g", "daemon off;"]
    labels:
      - traefik.backend=${COMPOSE_PROJECT_NAME}-de-nginx
      - traefik.docker.network=traefik_webgateway
      - traefik.frontend.rule=Host:${COMPOSE_PROJECT_NAME}-de.localhost
      - traefik.port=8080
    networks:
      - public
      - private
    volumes:
      - ${PWD}/testing/index.php:/var/www/index.php
      - ${PWD}/testing/vhost-de.conf:/etc/nginx/conf.d/default.conf
  php-de:
    image: jtreminio/php:7.2
    command: /usr/bin/php-fpm
    environment:
      - PHP.display_errors=1
    networks:
      - private
    volumes:
      - ${PWD}/testing/index.php:/var/www/index.php

  nginx-xdebug:
    image: nginx:alpine
    command: ["nginx", "-g", "daemon off;"]
    labels:
      - traefik.backend=${COMPOSE_PROJECT_NAME}-xdebug-nginx
      - traefik.docker.network=traefik_webgateway
      - traefik.frontend.rule=Host:${COMPOSE_PROJECT_NAME}-xdebug.localhost
      - traefik.port=8080
    networks:
      - public
      - private
    volumes:
      - ${PWD}/testing/index.php:/var/www/index.php
      - ${PWD}/testing/vhost-xdebug.conf:/etc/nginx/conf.d/default.conf
  php-xdebug:
    image: jtreminio/php:7.2
    command: /usr/bin/php-fpm
    environment:
      - PHP_INI_SCAN_DIR=:/p/xdebug
      - PHP.xdebug.remote_host=custom.localhost
    networks:
      - private
    volumes:
      - ${PWD}/testing/index.php:/var/www/index.php
